### ISSUE TITLE
transfer to wikidata org

### ISSUE THREAD

**Issue by ericprud** [Wikidata/triplify-json#1]
Here's a little code to convert wikidata JSON to RDF. There's more release engineering to go but ya gotta start somewhere. My intention is to transfer it to the wikidata org but maintain commit privs while i clean it up. @lydiapintscher, @lucaswerkmeister, @andrawaag

**Comment by andrawaag** [comment]
Our plan is to align this with the code in the Wikidata Integrator: https://github.com/SuLab/WikidataIntegrator/blob/main/notebooks/Wikidata_json2ttl.ipynb to be able to reproduce the RDF of Wikidata locally for local EntitySchema testing

**Comment by lucaswerkmeister** [comment]
Is this the same functionality as https://wb2rdf.toolforge.org/, but natively implemented in JS?

**Comment by andrawaag** [comment]
Yes, I think so.  The idea is to be able to apply EntitySchema's on adapted JSON blob's just before it is submitted back to the Wikidata API.  

I guess @ericprud  script aims at facilitating building RDF subsets from Wikidata.

**Comment by lydiapintscher** [comment]
I've sent you both invitations to the Wikidata org.

**Comment by ericprud** [comment]
tx. i started the transfer but i [got this message](https://github.com/ericprud/triplify-json/settings/transfer)
> You don’t have the permission to create public repositories on Wikidata

You might be able to accept the transfer.

**Comment by lydiapintscher** [comment]
Can you try again now?

**Comment by ericprud** [comment]
Check it out, this is `Wikidata/triplify-json/issues/1`

Tx!
